Repository WritelyForWriters/BE, pull requests merged in 2025-03, with the labels that each got.

#38 fix: discord appender load error
  api/src/main/resources/logback-spring.xml
Labels: fix

#39 fix: private method 에서 transactional 어노테이션 삭제
  api/src/main/java/writeon/api/auth/service/AuthCommandService.java
Labels: fix

#43 refactor: Modify res structure for get product list
  api/src/main/java/writeon/api/product/repository/ProductDao.java
  api/src/main/java/writeon/api/product/response/ProductResponse.java
Labels: refactor

#45 feat: spring security
  api/src/main/java/writeon/api/auth/helper/MemberHelper.java
  api/src/main/java/writeon/api/common/config/SecurityConfig.java
  api/src/main/java/writeon/api/common/config/WebConfig.java
  api/src/main/java/writeon/api/common/exception/CustomAuthenticationEntryPoint.java
  api/src/main/java/writeon/api/common/filter/CustomAuthenticationFilter.java
  api/src/main/java/writeon/api/common/resolver/AuthResolver.java
  api/src/main/java/writeon/api/member/controller/MemberController.java
  api/src/main/java/writeon/api/member/service/MemberQueryService.java
  build.gradle
  domain/src/main/java/writeon/domain/common/MemberSession.java
Labels: feat

#46 fix: AI 어시 기능 단계별 상태 저장 기능 수정
  api/src/main/java/writeon/api/assistant/controller/AssistantController.java
  api/src/main/java/writeon/api/assistant/request/AssistantCompletedRequest.java
  api/src/main/java/writeon/api/assistant/request/AssistantResearchRequest.java
  api/src/main/java/writeon/api/assistant/response/MessageCreateResponse.java
  api/src/main/java/writeon/api/assistant/service/AssistantService.java
  api/src/main/java/writeon/api/assistant/service/AutoModifyService.java
  api/src/main/java/writeon/api/assistant/service/FeedbackService.java
  api/src/main/java/writeon/api/assistant/service/ResearchService.java
  api/src/main/java/writeon/api/assistant/service/UserModifyService.java
  domain/src/main/java/writeon/domain/assistant/automodify/AutoModifyMessageJpaRepository.java
  domain/src/main/java/writeon/domain/assistant/enums/AssistantException.java
  domain/src/main/java/writeon/domain/assistant/feedback/FeedbackMessageJpaRepository.java
  domain/src/main/java/writeon/domain/assistant/usermodify/UserModifyMessageJpaRepository.java
Labels: fix

#47 fix: 비밀번호 규칙, swagger 수정
  api/src/main/java/writeon/api/auth/request/JoinRequest.java
  api/src/main/java/writeon/api/common/validation/IsPassword.java
  api/src/main/java/writeon/api/common/validation/IsPasswordValidator.java
  api/src/main/java/writeon/api/file/request/PresignedUrlIssueRequest.java
Labels: fix

#50 feat: Integrate research API with chat service
  api/src/main/java/writeon/api/assistant/controller/AssistantController.java
  api/src/main/java/writeon/api/assistant/service/ChatService.java
  api/src/main/java/writeon/api/assistant/service/ResearchService.java
  assistant-api-client/src/main/java/writeon/assistantapiclient/request/ResearchRequest.java
  domain/src/main/generated/writely/Keys.java
  domain/src/main/generated/writely/Public.java
  domain/src/main/generated/writely/Tables.java
  domain/src/main/generated/writely/tables/ResearchMessage.java
  domain/src/main/generated/writely/tables/pojos/ResearchMessage.java
  domain/src/main/generated/writely/tables/records/ResearchMessageRecord.java
  domain/src/main/java/writeon/domain/assistant/research/ResearchMessage.java
  domain/src/main/java/writeon/domain/assistant/research/ResearchMessageJpaRepository.java
Labels: feat

#51 feat: Apply security to product and assistant APIs
  api/src/main/java/writeon/api/assistant/service/AssistantService.java
  api/src/main/java/writeon/api/common/audit/CustomAuditorAware.java
  api/src/main/java/writeon/api/common/util/MemberUtil.java
  api/src/main/java/writeon/api/product/repository/ProductDao.java
  api/src/main/java/writeon/api/product/service/ProductCommandService.java
  api/src/main/java/writeon/api/product/service/ProductQueryService.java
  domain/src/main/java/writeon/domain/assistant/AssistantJpaRepository.java
  domain/src/main/java/writeon/domain/common/MemberSession.java
  domain/src/main/java/writeon/domain/product/repository/ProductJpaRepository.java
  domain/src/main/java/writeon/domain/product/repository/ProductMemoJpaRepository.java
Labels: feat

#52 fix: cert 갱신 스케쥴 변경
  .github/workflows/schedule-for-refresh-certification.yml
Labels: fix

#53 feat: add auth header button to swagger
  api/src/main/java/writeon/api/common/config/SwaggerConfig.java
Labels: feat

#54 fix: 비밀번호 변경 이메일 파라미터명 변경
  api/src/main/resources/templates/mail/change-password.html
Labels: fix

#55 feat: 닉네임 중복조회 API 기능 추가 및 인증 이슈 수정
  api/src/main/java/writeon/api/auth/controller/AuthController.java
  api/src/main/java/writeon/api/auth/request/CheckNicknameRequest.java
  api/src/main/java/writeon/api/auth/request/JoinRequest.java
  api/src/main/java/writeon/api/auth/response/CheckNicknameResponse.java
  api/src/main/java/writeon/api/auth/service/AuthCommandService.java
  api/src/main/java/writeon/api/auth/service/AuthQueryService.java
  api/src/main/java/writeon/api/common/validation/IsNickname.java
  api/src/main/java/writeon/api/common/validation/IsNicknameValidator.java
  domain/src/main/java/writeon/domain/auth/enums/AuthException.java
  domain/src/main/java/writeon/domain/member/repository/MemberJpaRepository.java
  domain/src/main/java/writeon/domain/member/repository/MemberPasswordJpaRepository.java
  sql/init.sql
Labels: fix

#56 fix: Update product response structure
  api/src/main/java/writeon/api/product/request/ProductMemoSaveRequest.java
  api/src/main/java/writeon/api/product/response/ProductDetailResponse.java
  api/src/main/java/writeon/api/product/response/ProductMemoResponse.java
  api/src/main/java/writeon/api/product/response/ProductResponse.java
  api/src/main/java/writeon/api/product/service/ProductCommandService.java
  docker-compose.yml
  domain/src/main/java/writeon/domain/product/ProductMemo.java
  sql/init.sql
Labels: fix

#57 fix: transaction error in Assistant API WebClient
  api/src/main/java/writeon/api/assistant/service/AssistantService.java
  api/src/main/java/writeon/api/assistant/service/AutoModifyService.java
  api/src/main/java/writeon/api/assistant/service/ChatService.java
  api/src/main/java/writeon/api/assistant/service/FeedbackService.java
  api/src/main/java/writeon/api/assistant/service/UserModifyService.java
  domain/src/main/java/writeon/domain/assistant/Assistant.java
  domain/src/main/java/writeon/domain/assistant/AssistantJpaRepository.java
  domain/src/main/java/writeon/domain/assistant/automodify/AutoModifyMessage.java
  domain/src/main/java/writeon/domain/assistant/chat/ChatMessage.java
  domain/src/main/java/writeon/domain/assistant/enums/AssistantType.java
  domain/src/main/java/writeon/domain/assistant/feedback/FeedbackMessage.java
  domain/src/main/java/writeon/domain/assistant/usermodify/UserModifyMessage.java
  sql/init.sql
Labels: fix

#59 fix: RefreshToken을 쿠키로 설정하도록 변경
  api/src/main/java/writeon/api/auth/controller/AuthController.java
  api/src/main/java/writeon/api/auth/helper/AuthCookieHelper.java
  api/src/main/java/writeon/api/auth/helper/JwtHelper.java
  api/src/main/java/writeon/api/auth/request/ReissueRequest.java
  api/src/main/java/writeon/api/auth/response/AuthTokenResponse.java
  api/src/main/java/writeon/api/auth/response/TokenReissueResponse.java
  api/src/main/java/writeon/api/auth/service/AuthCommandService.java
  domain/src/main/java/writeon/domain/auth/dto/AuthTokenDto.java
Labels: fix

#61 fix: logout security config 순서 변경
  api/src/main/java/writeon/api/common/config/SecurityConfig.java
Labels: fix
