Repository WritelyForWriters/BE, pull requests merged in 2025-02, with the labels that each got.

#22 refactor: product domain 수정
  sql/init.sql
  src/main/generated/writely/tables/ProductCustomField.java
  src/main/generated/writely/tables/pojos/ProductCustomField.java
  src/main/generated/writely/tables/records/ProductCustomFieldRecord.java
  src/main/java/com/writely/product/controller/ProductController.java
  src/main/java/com/writely/product/domain/ProductCustomField.java
  src/main/java/com/writely/product/domain/enums/ProductSectionType.java
  src/main/java/com/writely/product/request/ProductTemplateSaveRequest.java
  src/main/java/com/writely/product/response/ProductTemplateResponse.java
  src/main/java/com/writely/product/service/ProductCommandService.java
Labels: refactor

#23 fix: deploy에서 모든 컨테이너를 종료시키는 문제 해결
  .github/workflows/deploy.yml
Labels: fix

#27 refactor: memo table 구조 및 api 수정
  sql/init.sql
  src/main/generated/writely/tables/ProductMemo.java
  src/main/generated/writely/tables/pojos/ProductMemo.java
  src/main/generated/writely/tables/records/ProductMemoRecord.java
  src/main/java/com/writely/product/controller/ProductController.java
  src/main/java/com/writely/product/domain/ProductMemo.java
  src/main/java/com/writely/product/request/ProductMemoSaveRequest.java
  src/main/java/com/writely/product/response/ProductMemoResponse.java
  src/main/java/com/writely/product/service/ProductCommandService.java
  src/main/java/com/writely/product/service/ProductQueryService.java
Labels: refactor

#28 feat(email): 회원가입/비밀번호 재설정 이메일 컨텐츠 추가
  src/main/java/com/writely/auth/helper/MailHelper.java
  src/main/java/com/writely/auth/service/AuthCommandService.java
  src/main/resources/templates/mail/change-password.html
  src/main/resources/templates/mail/join.html
Labels: feat

#29 feat: 로그아웃
  src/main/java/com/writely/auth/controller/AuthController.java
  src/main/java/com/writely/auth/domain/RefreshToken.java
  src/main/java/com/writely/auth/repository/RefreshTokenRedisRepository.java
  src/main/java/com/writely/auth/service/AuthCommandService.java
Labels: feat

#32 refactor: terms_agree -> terms_agreement 로 변경
  sql/init.sql
  src/main/generated/writely/Keys.java
  src/main/generated/writely/Public.java
  src/main/generated/writely/Tables.java
  src/main/generated/writely/tables/TermsAgree.java
  src/main/generated/writely/tables/TermsAgreement.java
  src/main/generated/writely/tables/pojos/TermsAgreement.java
  src/main/generated/writely/tables/records/TermsAgreementRecord.java
Labels: refactor

#33 Feat/terms
  src/main/java/com/writely/auth/domain/JoinToken.java
  src/main/java/com/writely/auth/service/AuthCommandService.java
  src/main/java/com/writely/common/config/WebConfig.java
  src/main/java/com/writely/terms/controller/TermsController.java
  src/main/java/com/writely/terms/domain/TermsAgreeId.java
  src/main/java/com/writely/terms/domain/TermsAgreement.java
  src/main/java/com/writely/terms/domain/TermsAgreementId.java
  src/main/java/com/writely/terms/domain/enums/TermsCode.java
  src/main/java/com/writely/terms/repository/TermsAgreeJpaRepository.java
  src/main/java/com/writely/terms/repository/TermsDao.java
  src/main/java/com/writely/terms/response/TermsSummaryResponse.java
  src/main/java/com/writely/terms/service/TermsQueryService.java
Labels: feat
