Repository WritelyForWriters/BE, pull requests merged in 2025-01, with the labels that each got.

#2 feat: 응답 로직 개선 (공통 처리)
  src/main/java/com/writely/common/response/GlobalResponseBodyHandler.java
  src/main/java/com/writely/product/controller/ProductController.java
Labels: refactor

#5 feat: add product api
  build.gradle
  sql/init.sql
  src/main/java/com/writely/product/controller/ProductController.java
  src/main/java/com/writely/product/domain/Product.java
  src/main/java/com/writely/product/domain/ProductCharacter.java
  src/main/java/com/writely/product/domain/ProductCustomField.java
  src/main/java/com/writely/product/domain/ProductIdeaNote.java
  src/main/java/com/writely/product/domain/ProductMemo.java
  src/main/java/com/writely/product/domain/ProductPlot.java
  src/main/java/com/writely/product/domain/ProductSynopsis.java
  src/main/java/com/writely/product/domain/ProductWorldview.java
  src/main/java/com/writely/product/domain/enums/ProductException.java
  src/main/java/com/writely/product/repository/ProductCharacterRepository.java
  src/main/java/com/writely/product/repository/ProductCustomFieldRepository.java
  src/main/java/com/writely/product/repository/ProductDao.java
  src/main/java/com/writely/product/repository/ProductIdeaNoteRepository.java
  src/main/java/com/writely/product/repository/ProductPlotRepository.java
  src/main/java/com/writely/product/repository/ProductSynopsisRepository.java
  src/main/java/com/writely/product/repository/ProductWorldviewRepository.java
  src/main/java/com/writely/product/request/ProductMemoCreateRequest.java
  src/main/java/com/writely/product/request/ProductModifyRequest.java
  src/main/java/com/writely/product/request/ProductTemplateCreateRequest.java
  src/main/java/com/writely/product/response/ProductDetailResponse.java
  src/main/java/com/writely/product/response/ProductMemoResponse.java
  src/main/java/com/writely/product/response/ProductResponse.java
  src/main/java/com/writely/product/response/ProductTemplateResponse.java
  src/main/java/com/writely/product/service/ProductCommandService.java
  src/main/java/com/writely/product/service/ProductQueryService.java
Labels: feat

#10 feat: auth
  build.gradle
  sql/init.sql
  src/main/java/com/writely/WritelyApplication.java
  src/main/java/com/writely/auth/controller/AuthController.java
  src/main/java/com/writely/auth/domain/BaseToken.java
  src/main/java/com/writely/auth/domain/JoinToken.java
  src/main/java/com/writely/auth/domain/JwtPayload.java
  src/main/java/com/writely/auth/domain/RefreshToken.java
  src/main/java/com/writely/auth/domain/enums/AuthException.java
  src/main/java/com/writely/auth/helper/JwtHelper.java
  src/main/java/com/writely/auth/helper/MailHelper.java
  src/main/java/com/writely/auth/repository/JoinTokenRedisRepository.java
  src/main/java/com/writely/auth/repository/RefreshTokenRedisRepository.java
  src/main/java/com/writely/auth/request/JoinRequest.java
  src/main/java/com/writely/auth/request/JoinTokenRequest.java
  src/main/java/com/writely/auth/request/LoginRequest.java
  src/main/java/com/writely/auth/request/ReissueRequest.java
  src/main/java/com/writely/auth/response/AuthTokenResponse.java
  src/main/java/com/writely/auth/service/AuthCommandService.java
  src/main/java/com/writely/auth/service/AuthQueryService.java
  src/main/java/com/writely/common/util/CryptoUtil.java
  src/main/java/com/writely/member/domain/Member.java
  src/main/java/com/writely/member/domain/MemberPassword.java
  src/main/java/com/writely/member/repository/MemberJpaRepository.java
  src/main/java/com/writely/member/repository/MemberPasswordJpaRepository.java
  src/main/java/com/writely/product/repository/ProductCharacterJpaRepository.java
  src/main/java/com/writely/product/repository/ProductCustomFieldJpaRepository.java
  src/main/java/com/writely/product/repository/ProductIdeaNoteJpaRepository.java
  src/main/java/com/writely/product/repository/ProductJpaRepository.java
  src/main/java/com/writely/product/repository/ProductMemoJpaRepository.java
  src/main/java/com/writely/product/repository/ProductPlotJpaRepository.java
  src/main/java/com/writely/product/repository/ProductRepository.java
  src/main/java/com/writely/product/repository/ProductSynopsisJpaRepository.java
  src/main/java/com/writely/product/repository/ProductWorldviewJpaRepository.java
  src/main/java/com/writely/product/service/ProductCommandService.java
  src/main/java/com/writely/product/service/ProductQueryService.java
  src/main/resources/templates/mail/chpw.html
  src/main/resources/templates/mail/join.html
Labels: feat

#12 fix: 존재하는 api 경로만 error log 전송하도록 수정
  .github/workflows/build-test.yml
  src/main/java/com/writely/common/discord/DiscordLogAppender.java
  src/main/java/com/writely/common/filter/MDCFilter.java
  src/main/java/com/writely/common/util/MDCUtil.java
Labels: fix

#15 refactor: PR(#13)
  src/main/java/com/writely/common/config/WebConfig.java
  src/main/java/com/writely/member/response/MyProfileResponse.java
Labels: refactor

#16 feat(auth): validation
  build.gradle
  sql/init.sql
  src/main/generated/writely/Keys.java
  src/main/generated/writely/Public.java
  src/main/generated/writely/Tables.java
  src/main/generated/writely/tables/AutoModifyMessage.java
  src/main/generated/writely/tables/Member.java
  src/main/generated/writely/tables/pojos/AutoModifyMessage.java
  src/main/generated/writely/tables/pojos/Member.java
  src/main/generated/writely/tables/records/AutoModifyMessageRecord.java
  src/main/generated/writely/tables/records/MemberRecord.java
  src/main/java/com/writely/auth/controller/AuthController.java
  src/main/java/com/writely/auth/request/JoinRequest.java
  src/main/java/com/writely/auth/request/JoinTokenRequest.java
  src/main/java/com/writely/auth/request/LoginRequest.java
  src/main/java/com/writely/auth/request/ReissueRequest.java
  src/main/java/com/writely/auth/response/AuthTokenResponse.java
  src/main/java/com/writely/auth/service/AuthCommandService.java
  src/main/java/com/writely/common/enums/code/ResultCodeInfo.java
  src/main/java/com/writely/common/exception/GlobalExceptionHandler.java
  src/main/java/com/writely/common/response/BaseResponse.java
  src/main/java/com/writely/common/validation/IsEmail.java
  src/main/java/com/writely/common/validation/IsEmailValidator.java
  src/main/java/com/writely/common/validation/IsPassword.java
  src/main/java/com/writely/common/validation/IsPasswordValidator.java
  src/main/java/com/writely/member/domain/Member.java
  src/main/java/com/writely/member/response/MyProfileResponse.java
Labels: feat

#17 refactor(log): stacktrace를 파라미터로 하는 오버로딩 함수 추가
  src/main/java/com/writely/auth/service/AuthCommandService.java
  src/main/java/com/writely/common/exception/GlobalExceptionHandler.java
  src/main/java/com/writely/common/util/LogUtil.java
Labels: refactor
