Repository WritelyForWriters/BE, pull requests merged in 2025-04, with the labels that each got.

#65 style: 이메일 문구 변경
  api/src/main/java/writeon/api/auth/helper/MailHelper.java
  api/src/main/resources/templates/mail/change-password.html
  api/src/main/resources/templates/mail/join.html
Labels: fix

#66 fix: 로그인 관련 에러메시지 처리
  api/src/main/java/writeon/api/auth/response/LoginFailResponse.java
  api/src/main/java/writeon/api/auth/service/AuthCommandService.java
  api/src/main/java/writeon/api/common/exception/BaseException.java
  api/src/main/java/writeon/api/common/exception/handler/GlobalExceptionHandler.java
  api/src/main/java/writeon/api/common/response/BaseResponse.java
  api/src/main/java/writeon/api/common/util/DateTimeUtil.java
  domain/src/main/generated/writeon/Keys.java
  domain/src/main/generated/writeon/Public.java
  domain/src/main/generated/writeon/Routines.java
  domain/src/main/generated/writeon/Tables.java
  domain/src/main/generated/writeon/tables/Assistant.java
  domain/src/main/generated/writeon/tables/PgpArmorHeaders.java
  domain/src/main/generated/writeon/tables/pojos/Assistant.java
  domain/src/main/generated/writeon/tables/pojos/PgpArmorHeaders.java
  domain/src/main/generated/writeon/tables/records/AssistantRecord.java
  domain/src/main/generated/writeon/tables/records/PgpArmorHeadersRecord.java
  domain/src/main/java/writeon/domain/auth/enums/AuthException.java
Labels: fix

#67 fix: 이미지 타임존 설정
  Dockerfile
Labels: fix

#69 style: 로그인 5회 경고 에러 메시지 수정
  domain/src/main/java/writeon/domain/auth/enums/AuthException.java
Labels: fix

#70 refactor: availableLoginAt -> loginAvailableAt 응답 변경
  api/src/main/java/writeon/api/auth/response/LoginFailResponse.java
Labels: refactor

#71 feat: add assistant planner generate API
  api/src/main/java/writeon/api/assistant/controller/AssistantController.java
  api/src/main/java/writeon/api/assistant/request/AssistantPlannerMessageRequest.java
  api/src/main/java/writeon/api/assistant/service/PlannerService.java
  assistant-api-client/src/main/java/writeon/assistantapiclient/AssistantApiClient.java
  assistant-api-client/src/main/java/writeon/assistantapiclient/request/PlannerGenerateRequest.java
  domain/build.gradle
  domain/src/main/generated/writeon/Keys.java
  domain/src/main/generated/writeon/Public.java
  domain/src/main/generated/writeon/Tables.java
  domain/src/main/generated/writeon/tables/AssistantPlannerMessage.java
  domain/src/main/generated/writeon/tables/pojos/AssistantPlannerMessage.java
  domain/src/main/generated/writeon/tables/records/AssistantPlannerMessageRecord.java
  domain/src/main/java/writeon/domain/assistant/AssistantMessage.java
  domain/src/main/java/writeon/domain/assistant/AssistantPlannerMessage.java
  domain/src/main/java/writeon/domain/assistant/AssistantPlannerMessageJpaRepository.java
  domain/src/main/java/writeon/domain/assistant/enums/AssistantType.java
  sql/init.sql
Labels: feat

#73 refactor: change get assistant histories API to cursor pagination with UUIDv7 PK
  api/src/main/java/writeon/api/assistant/controller/AssistantController.java
  api/src/main/java/writeon/api/assistant/repository/AssistantDao.java
  api/src/main/java/writeon/api/assistant/request/AssistantHistoryListRequest.java
  api/src/main/java/writeon/api/assistant/service/AssistantService.java
  api/src/main/java/writeon/api/common/request/OffsetRequest.java
  api/src/main/java/writeon/api/common/response/CursorResponse.java
  api/src/main/java/writeon/api/common/response/OffsetResponse.java
  domain/build.gradle
  domain/src/main/java/writeon/domain/assistant/Assistant.java
  domain/src/main/java/writeon/domain/assistant/AssistantMessage.java
  domain/src/main/java/writeon/domain/product/Product.java
  domain/src/main/java/writeon/domain/product/ProductCharacter.java
  domain/src/main/java/writeon/domain/product/ProductCustomField.java
  domain/src/main/java/writeon/domain/product/ProductFavoritePrompt.java
  domain/src/main/java/writeon/domain/product/ProductMemo.java
  domain/src/main/java/writeon/domain/product/ProductPlot.java
  sql/init.sql
Labels: refactor

#74 fix: send mail asynchronously
  api/src/main/java/writeon/api/auth/helper/MailHelper.java
  api/src/main/java/writeon/api/common/config/AsyncConfig.java
Labels: fix

#75 fix: modify query condition for assistant histories
  api/src/main/java/writeon/api/assistant/repository/AssistantDao.java
  api/src/main/java/writeon/api/assistant/response/AssistantHistoryResponse.java
  api/src/main/java/writeon/api/product/service/ProductQueryService.java
Labels: fix

#76 feat: add isFavoritedPrompt field to assistant histories response
  api/src/main/java/writeon/api/assistant/repository/AssistantDao.java
  api/src/main/java/writeon/api/assistant/response/AssistantHistoryResponse.java
  api/src/main/java/writeon/api/assistant/service/AssistantService.java
  api/src/main/java/writeon/api/assistant/service/AutoModifyService.java
  api/src/main/java/writeon/api/assistant/service/ChatService.java
  api/src/main/java/writeon/api/assistant/service/FeedbackService.java
  api/src/main/java/writeon/api/assistant/service/PlannerService.java
  api/src/main/java/writeon/api/assistant/service/UserModifyService.java
  api/src/main/java/writeon/api/product/controller/ProductController.java
  api/src/main/java/writeon/api/product/repository/ProductDao.java
  api/src/main/java/writeon/api/product/request/ProductFavoritePromptCreateRequest.java
  api/src/main/java/writeon/api/product/response/ProductFavoritePromptResponse.java
  api/src/main/java/writeon/api/product/service/ProductCommandService.java
  api/src/main/java/writeon/api/product/service/ProductQueryService.java
  domain/src/main/generated/writeon/tables/ProductFavoritePrompt.java
  domain/src/main/generated/writeon/tables/pojos/ProductFavoritePrompt.java
  domain/src/main/generated/writeon/tables/records/ProductFavoritePromptRecord.java
  domain/src/main/java/writeon/domain/assistant/AssistantMessageJpaRepository.java
  domain/src/main/java/writeon/domain/product/ProductFavoritePrompt.java
  domain/src/main/java/writeon/domain/product/enums/ProductException.java
  domain/src/main/java/writeon/domain/product/repository/ProductFavoritePromptJpaRepository.java
  sql/init.sql
Labels: feat

#77 fix: favorite prompt delete not working
  api/src/main/java/writeon/api/product/service/ProductCommandService.java
  domain/src/main/java/writeon/domain/product/Product.java
  domain/src/main/java/writeon/domain/product/ProductFavoritePrompt.java
Labels: fix

#78 fix: resolve assistant APIs error
  api/src/main/java/writeon/api/assistant/service/AutoModifyService.java
  api/src/main/java/writeon/api/assistant/service/ChatService.java
  api/src/main/java/writeon/api/assistant/service/DocumentUploadService.java
  api/src/main/java/writeon/api/assistant/service/FeedbackService.java
  api/src/main/java/writeon/api/assistant/service/PlannerService.java
  api/src/main/java/writeon/api/assistant/service/UserModifyService.java
  domain/src/main/java/writeon/domain/assistant/AssistantPlannerMessage.java
Labels: fix

#81 fix: resolve get planner api issue
  api/src/main/java/writeon/api/product/request/ProductTemplateSaveRequest.java
  api/src/main/java/writeon/api/product/response/ProductTemplateResponse.java
  api/src/main/java/writeon/api/product/service/ProductCommandService.java
  assistant-api-client/src/main/java/writeon/assistantapiclient/request/UserSetting.java
  domain/src/main/java/writeon/domain/product/ProductCharacter.java
  sql/init.sql
Labels: fix

#82 fix: 어시트턴트 사용 내역 조회에서 웹 검색 사용 내역이 조회되지 않는 이슈 해결
  api/src/main/java/writeon/api/assistant/service/ChatService.java
  domain/src/main/generated/writeon/tables/ProductCharacter.java
  domain/src/main/generated/writeon/tables/ProductSynopsis.java
  domain/src/main/generated/writeon/tables/pojos/ProductCharacter.java
  domain/src/main/generated/writeon/tables/records/ProductCharacterRecord.java
Labels: fix

#83 feat: 어시스턴트 사용 내역 응답에 평가 데이터 추가
  api/src/main/java/writeon/api/assistant/repository/AssistantDao.java
  api/src/main/java/writeon/api/assistant/response/AssistantHistoryResponse.java
Labels: feat
